export type RequestErrorCode =
  | "REQUEST_NOT_FOUND"
  | "REQUEST_COMMUNITY_PUBLISHER_FORBIDDEN"
  | "REQUEST_TEAM_PUBLISHER_FORBIDDEN"
  | "REQUEST_ATHLETES_PUBLISHER_FORBIDDEN"
  | "REQUEST_AUDIENCE_MEMBERSHIP_REQUIRED"
  | "REQUEST_NOT_RESPONDABLE"
  | "REQUEST_SELF_RESPONSE_FORBIDDEN"
  | "REQUEST_RESPONSE_ALREADY_EXISTS"
  | "REQUEST_RESPONSE_NOT_PENDING"
  | "REQUEST_RESPONSE_NOT_WITHDRAWABLE"
  | "REQUEST_STATUS_CONFLICT"
  | "REQUEST_NOT_MUTABLE"
  | "REQUEST_TAXONOMY_INVALID"
  | "REQUEST_PRODUCT_METADATA_FORBIDDEN"
  | "REQUEST_CUSTOM_NEED_FORBIDDEN"
  | "REQUEST_CUSTOM_NEED_REQUIRED"
  | "REQUEST_IMAGE_NOT_FOUND"
  | "REQUEST_IMAGE_REQUIRED"
  | "REQUEST_IMAGE_TYPE_INVALID"
  | "REQUEST_IMAGE_TOO_LARGE"
  | "REQUEST_IMAGE_STORAGE_NOT_CONFIGURED"
  | "REQUEST_IMAGE_UPLOAD_FAILED"
  | "REQUEST_IMAGE_UNAVAILABLE";

export class RequestError extends Error {
  override readonly name = "RequestError";

  constructor(
    readonly code: RequestErrorCode,
    message: string,
  ) {
    super(message);
  }
}
