import type { RidePolicyErrorCode } from "./ride-policy.js";

export type RideErrorCode =
  | RidePolicyErrorCode
  | "RIDE_OFFER_NOT_FOUND"
  | "RIDE_OFFER_NOT_MUTABLE"
  | "RIDE_REQUEST_NOT_FOUND"
  | "RIDE_REQUEST_NOT_MUTABLE"
  | "RIDE_PARTICIPATION_NOT_AVAILABLE"
  | "RIDE_PARTICIPATION_NOT_FOUND"
  | "RIDE_PARTICIPATION_CANCEL_FORBIDDEN"
  | "RIDE_MEETING_POINT_NOT_AVAILABLE"
  | "RIDE_MEETING_POINT_FORBIDDEN"
  | "RIDE_VEHICLE_PHOTO_NOT_FOUND"
  | "RIDE_VEHICLE_PHOTO_REQUIRED"
  | "RIDE_VEHICLE_PHOTO_TYPE_INVALID"
  | "RIDE_VEHICLE_PHOTO_TOO_LARGE"
  | "RIDE_VEHICLE_PHOTO_STORAGE_NOT_CONFIGURED"
  | "RIDE_VEHICLE_PHOTO_UPLOAD_FAILED"
  | "RIDE_VEHICLE_PHOTO_UNAVAILABLE"
  | "RIDE_OFFER_STATUS_NOT_CHANGED"
  | "RIDE_REQUEST_STATUS_NOT_CHANGED"
  | "RIDE_PARTICIPATION_STATUS_NOT_CHANGED"
  | "RIDE_OFFER_MANAGE_FORBIDDEN"
  | "RIDE_REQUEST_MANAGE_FORBIDDEN"
  | "RIDE_DESTINATION_EVENT_NOT_FOUND"
  | "RIDE_DESTINATION_PLACE_NOT_FOUND"
  | "RIDE_REQUEST_COMMUNITY_TARGET_FORBIDDEN"
  | "RIDE_REQUEST_COMMUNITY_AUDIENCE_EMPTY"
  | "RIDE_REQUEST_COMMUNITY_FEED_FORBIDDEN";

export class RideError extends Error {
  constructor(
    public readonly code: RideErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "RideError";
  }
}
