export type GearUpErrorCode =
  | "GEAR_UP_SHOP_NOT_FOUND"
  | "GEAR_UP_MANAGE_FORBIDDEN"
  | "GEAR_UP_REVIEW_NOT_PENDING"
  | "GEAR_UP_PRODUCT_NOT_FOUND"
  | "GEAR_UP_PRODUCT_MANAGE_FORBIDDEN"
  | "GEAR_UP_PRODUCT_MEDIA_MANAGE_FORBIDDEN"
  | "GEAR_UP_PRODUCT_IMAGE_TYPE_INVALID"
  | "GEAR_UP_PRODUCT_IMAGE_REQUIRED"
  | "GEAR_UP_PRODUCT_IMAGE_TOO_LARGE"
  | "GEAR_UP_PRODUCT_IMAGE_STORAGE_NOT_CONFIGURED"
  | "GEAR_UP_PRODUCT_IMAGE_UPLOAD_FAILED"
  | "GEAR_UP_PRODUCT_IMAGE_NOT_FOUND"
  | "GEAR_UP_PRODUCT_IMAGE_UNAVAILABLE"
  | "GEAR_UP_PRODUCT_IMAGE_LIMIT_REACHED"
  | "GEAR_UP_PRODUCT_IMAGE_ORDER_INVALID";

export class GearUpError extends Error {
  override readonly name = "GearUpError";

  constructor(
    readonly code: GearUpErrorCode,
    message: string,
  ) {
    super(message);
  }
}
