-- Sport taxonomy completion for the sport-first Requests branch.
-- Each sport exposes realistic needs for that sport instead of one copied generic list,
-- every sport branch ends in an `Other` escape hatch with allowsCustomText = true, and
-- several sports gain the Community Support branch they were missing.
-- Existing needs are untouched; only additions are made.
-- Surface rule mirrors the existing seed: Football needs are PLAY-eligible, no other sport is.

INSERT INTO "HelpTaxonomySubcategory"
  ("id", "requestType", "sport", "slug", "label", "sortOrder", "active", "createdAt", "updatedAt")
VALUES
  ('hts-running-support', 'SPORT'::"HelpRequestType", 'RUNNING'::"AthletesSport", 'community-support', 'Community Support', 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('hts-cycling-support', 'SPORT'::"HelpRequestType", 'CYCLING'::"AthletesSport", 'community-support', 'Community Support', 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('hts-swimming-support', 'SPORT'::"HelpRequestType", 'SWIMMING'::"AthletesSport", 'community-support', 'Community Support', 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('hts-basketball-support', 'SPORT'::"HelpRequestType", 'BASKETBALL'::"AthletesSport", 'community-support', 'Community Support', 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('hts-tennis-support', 'SPORT'::"HelpRequestType", 'TENNIS'::"AthletesSport", 'community-support', 'Community Support', 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('hts-padel-support', 'SPORT'::"HelpRequestType", 'PADEL'::"AthletesSport", 'community-support', 'Community Support', 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('hts-other-roles', 'SPORT'::"HelpRequestType", 'OTHER'::"AthletesSport", 'community-roles', 'Community Roles', 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "HelpTaxonomyNeed"
  ("id", "subcategoryId", "slug", "label", "kind", "allowsCustomText", "sortOrder", "active", "createdAt", "updatedAt")
VALUES
  ('htn-football-roles-player', 'hts-football-roles', 'player', 'Player', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-roles-assistant-coach', 'hts-football-roles', 'assistant-coach', 'Assistant Coach', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-roles-training-partner', 'hts-football-roles', 'training-partner', 'Training Partner', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-roles-other', 'hts-football-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-support-training-group', 'hts-football-support', 'training-group', 'Training Group', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 20, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-support-training-session', 'hts-football-support', 'training-session', 'Training Session', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-support-squad-help', 'hts-football-support', 'squad-help', 'Team & Squad Help', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-support-friendly-opponent', 'hts-football-support', 'friendly-opponent', 'Friendly & Opponent', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-support-advice', 'hts-football-support', 'advice', 'Advice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 60, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-support-skill-practice', 'hts-football-support', 'skill-practice', 'Skill Practice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 70, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-support-fitness-partner', 'hts-football-support', 'fitness-partner', 'Fitness & Conditioning Partner', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 80, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-football-support-other', 'hts-football-support', 'other', 'Other', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", true, 90, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-running-roles-coach', 'hts-running-roles', 'coach', 'Coach', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-running-roles-other', 'hts-running-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-running-support-training-group', 'hts-running-support', 'training-group', 'Training Group', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-running-support-training-session', 'hts-running-support', 'training-session', 'Training Session', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 20, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-running-support-route-advice', 'hts-running-support', 'route-advice', 'Route Advice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-running-support-conditioning', 'hts-running-support', 'conditioning', 'Conditioning', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-running-support-other', 'hts-running-support', 'other', 'Other', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-cycling-roles-coach', 'hts-cycling-roles', 'coach', 'Coach', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-cycling-roles-other', 'hts-cycling-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-cycling-support-group-ride', 'hts-cycling-support', 'group-ride', 'Group Ride', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-cycling-support-training-session', 'hts-cycling-support', 'training-session', 'Training Session', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 20, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-cycling-support-route-advice', 'hts-cycling-support', 'route-advice', 'Route Advice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-cycling-support-mechanical-help', 'hts-cycling-support', 'mechanical-help', 'Mechanical Help', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-cycling-support-other', 'hts-cycling-support', 'other', 'Other', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-swimming-roles-coach', 'hts-swimming-roles', 'coach', 'Coach', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-swimming-roles-training-partner', 'hts-swimming-roles', 'training-partner', 'Training Partner', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-swimming-roles-other', 'hts-swimming-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-swimming-support-training-group', 'hts-swimming-support', 'training-group', 'Training Group', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-swimming-support-training-session', 'hts-swimming-support', 'training-session', 'Training Session', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 20, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-swimming-support-technique-advice', 'hts-swimming-support', 'technique-advice', 'Technique Advice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-swimming-support-other', 'hts-swimming-support', 'other', 'Other', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", true, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-basketball-roles-teammate', 'hts-basketball-roles', 'teammate', 'Teammate', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-basketball-roles-referee', 'hts-basketball-roles', 'referee', 'Referee', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-basketball-roles-other', 'hts-basketball-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-basketball-support-pickup-game', 'hts-basketball-support', 'pickup-game', 'Pickup Game', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-basketball-support-training-group', 'hts-basketball-support', 'training-group', 'Training Group', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 20, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-basketball-support-training-session', 'hts-basketball-support', 'training-session', 'Training Session', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-basketball-support-advice', 'hts-basketball-support', 'advice', 'Advice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-basketball-support-other', 'hts-basketball-support', 'other', 'Other', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-tennis-roles-playing-partner', 'hts-tennis-roles', 'playing-partner', 'Playing Partner', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-tennis-roles-doubles-partner', 'hts-tennis-roles', 'doubles-partner', 'Doubles Partner', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-tennis-roles-other', 'hts-tennis-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-tennis-support-training-group', 'hts-tennis-support', 'training-group', 'Training Group', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-tennis-support-training-session', 'hts-tennis-support', 'training-session', 'Training Session', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 20, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-tennis-support-advice', 'hts-tennis-support', 'advice', 'Advice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-tennis-support-skill-practice', 'hts-tennis-support', 'skill-practice', 'Skill Practice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-tennis-support-other', 'hts-tennis-support', 'other', 'Other', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-padel-roles-coach', 'hts-padel-roles', 'coach', 'Coach', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-padel-roles-doubles-partner', 'hts-padel-roles', 'doubles-partner', 'Doubles Partner', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-padel-roles-other', 'hts-padel-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-padel-support-training-group', 'hts-padel-support', 'training-group', 'Training Group', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-padel-support-training-session', 'hts-padel-support', 'training-session', 'Training Session', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 20, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-padel-support-advice', 'hts-padel-support', 'advice', 'Advice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-padel-support-other', 'hts-padel-support', 'other', 'Other', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", true, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-gym-roles-training-partner', 'hts-gym-roles', 'training-partner', 'Training Partner', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", false, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-gym-roles-other', 'hts-gym-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 50, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-gym-support-training-session', 'hts-gym-support', 'training-session', 'Training Session', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 20, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-gym-support-programme-advice', 'hts-gym-support', 'programme-advice', 'Programme Advice', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", false, 30, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-gym-support-other', 'hts-gym-support', 'other', 'Other', 'COMMUNITY_SUPPORT'::"HelpTaxonomyNeedKind", true, 40, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
  ('htn-other-roles-other', 'hts-other-roles', 'other', 'Other', 'COMMUNITY_ROLE'::"HelpTaxonomyNeedKind", true, 10, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO "HelpTaxonomyNeedSurface" ("needId", "surface")
VALUES
  ('htn-football-roles-player', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-roles-player', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-roles-player', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-roles-assistant-coach', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-roles-assistant-coach', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-roles-assistant-coach', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-roles-training-partner', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-roles-training-partner', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-roles-training-partner', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-roles-other', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-roles-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-support-training-group', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-support-training-group', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-support-training-group', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-support-training-session', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-support-training-session', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-support-training-session', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-support-squad-help', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-support-squad-help', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-support-squad-help', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-support-friendly-opponent', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-support-friendly-opponent', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-support-friendly-opponent', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-support-advice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-support-advice', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-support-advice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-support-skill-practice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-support-skill-practice', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-support-skill-practice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-support-fitness-partner', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-support-fitness-partner', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-support-fitness-partner', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-football-support-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-football-support-other', 'PLAY'::"HelpTaxonomySurface"),
  ('htn-football-support-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-running-roles-coach', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-running-roles-coach', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-running-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-running-roles-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-running-support-training-group', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-running-support-training-group', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-running-support-training-session', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-running-support-training-session', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-running-support-route-advice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-running-support-route-advice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-running-support-conditioning', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-running-support-conditioning', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-running-support-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-running-support-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-cycling-roles-coach', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-cycling-roles-coach', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-cycling-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-cycling-roles-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-cycling-support-group-ride', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-cycling-support-group-ride', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-cycling-support-training-session', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-cycling-support-training-session', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-cycling-support-route-advice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-cycling-support-route-advice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-cycling-support-mechanical-help', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-cycling-support-mechanical-help', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-cycling-support-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-cycling-support-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-swimming-roles-coach', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-swimming-roles-coach', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-swimming-roles-training-partner', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-swimming-roles-training-partner', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-swimming-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-swimming-roles-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-swimming-support-training-group', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-swimming-support-training-group', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-swimming-support-training-session', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-swimming-support-training-session', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-swimming-support-technique-advice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-swimming-support-technique-advice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-swimming-support-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-swimming-support-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-basketball-roles-teammate', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-basketball-roles-teammate', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-basketball-roles-referee', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-basketball-roles-referee', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-basketball-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-basketball-roles-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-basketball-support-pickup-game', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-basketball-support-pickup-game', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-basketball-support-training-group', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-basketball-support-training-group', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-basketball-support-training-session', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-basketball-support-training-session', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-basketball-support-advice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-basketball-support-advice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-basketball-support-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-basketball-support-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-tennis-roles-playing-partner', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-tennis-roles-playing-partner', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-tennis-roles-doubles-partner', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-tennis-roles-doubles-partner', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-tennis-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-tennis-roles-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-tennis-support-training-group', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-tennis-support-training-group', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-tennis-support-training-session', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-tennis-support-training-session', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-tennis-support-advice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-tennis-support-advice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-tennis-support-skill-practice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-tennis-support-skill-practice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-tennis-support-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-tennis-support-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-padel-roles-coach', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-padel-roles-coach', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-padel-roles-doubles-partner', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-padel-roles-doubles-partner', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-padel-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-padel-roles-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-padel-support-training-group', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-padel-support-training-group', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-padel-support-training-session', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-padel-support-training-session', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-padel-support-advice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-padel-support-advice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-padel-support-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-padel-support-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-gym-roles-training-partner', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-gym-roles-training-partner', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-gym-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-gym-roles-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-gym-support-training-session', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-gym-support-training-session', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-gym-support-programme-advice', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-gym-support-programme-advice', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-gym-support-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-gym-support-other', 'ATHLETES'::"HelpTaxonomySurface"),
  ('htn-other-roles-other', 'REQUESTS'::"HelpTaxonomySurface"),
  ('htn-other-roles-other', 'ATHLETES'::"HelpTaxonomySurface");
