export type EventErrorCode =
  | "EVENT_NOT_FOUND"
  | "COMMUNITY_REQUIRED"
  | "PLACE_REQUIRED"
  | "EVENT_MANAGE_FORBIDDEN"
  | "EVENT_PAYMENTS_NOT_ENABLED"
  | "EVENT_NOT_EDITABLE"
  | "EVENT_TIME_INVALID"
  | "WATCH_CULTURAL_OWNER_REQUIRED"
  | "WATCH_EVENT_KIND_IMMUTABLE"
  | "EVENT_NOT_CANCELLABLE"
  | "EVENT_NOT_COMPLETABLE"
  | "EVENT_FULL"
  | "EVENT_NOT_ACTIVE"
  | "RSVP_ALREADY_ATTENDED"
  | "EVENT_MEMBER_CONTENT_FORBIDDEN"
  | "EVENT_FORMATION_INVALID_PLAYER"
  | "EVENT_FORMATION_DUPLICATE_PLAYER"
  | "EVENT_CHECK_IN_REQUIRES_CONFIRMED_RSVP"
  | "EVENT_CHAT_FORBIDDEN"
  | "EVENT_CHAT_INACTIVE";

export class EventError extends Error {
  constructor(
    public readonly code: EventErrorCode,
    message: string,
  ) {
    super(message);
    this.name = "EventError";
  }
}
